# https://taskfile.dev

version: "3"

silent: true

vars:
  packages: ("User")

tasks:
  default:
    cmds:
      - task --list

  feature:
    desc: Create a feature branch
    cmds:
      - git checkout main
      - git pull
      - git checkout -b feature/{{ .name }}

  lint:
    desc: Lint packages with Helm
    deps: [has:helm]
    cmds:
      - |
        pkgs={{.packages}}
        for i in "${pkgs[@]}"
        do 
          task lint:package pkg=$i; 
        done

  # Private tasks
  lint:package:
    cmds:
      - helm lint {{ .pkg }}

  has:helm:
    preconditions:
      - sh: command -v helm
        msg: Install Helm first
