# https://taskfile.dev

version: "3"

silent: true

vars:
  BLUE: '\033[0;34m'
  GREEN: '\033[0;32m'
  NC: '\033[0m' # No Color

tasks:
  default:
    cmds:
      - task --list

  build:
    desc: Build packages and index
    cmds:
      - echo -e "{{ .BLUE }}Generating packages and index{{ .NC }}"
      - task: build:packages
      - task: build:index
  
  build:packages:
    cmds:
      - mkdir -p packages
      - helm package User --destination packages 

  build:index:
    dir: packages
    cmds:
      - helm repo index .
      - 'echo -e "{{ .GREEN }}Successfully generated index and saved it to: packages/index.yaml{{ .NC }}"'
