apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "cronjob.fullname" . }}
  labels:
    {{- include "cronjob.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.schedule | quote }}
  jobTemplate:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "cronjob.selectorLabels" . | nindent 8 }}
    spec:
      template:
        {{- with .Values.imagePullSecrets }}
        imagePullSecrets:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        serviceAccountName: {{ include "cronjob.serviceAccountName" . }}
        securityContext:
          {{- toYaml .Values.podSecurityContext | nindent 10 }}
        containers:
          - name: {{ .Chart.Name }}
            securityContext:
              {{- toYaml .Values.securityContext | nindent 14 }}
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            {{- with .Values.volumeMounts }}
            volumeMounts:
              {{- toYaml . | nindent 14 }}
            {{- end }}
            resources:
              {{- toYaml .Values.resources | nindent 14 }}
            {{- with .Values.env }}
            env:
              {{- toYaml . | nindent 14 }}
            {{- end }}
            {{- with .Values.envFrom }}
            envFrom:
              {{- toYaml . | nindent 14 }}
            {{- end }}
        {{- with .Values.nodeSelector }}
        nodeSelector:
          {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.affinity }}
        affinity:
          {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.tolerations }}
        tolerations:
          {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.volumes }}
        volumes:
          {{- toYaml . | nindent 8 }}
        {{- end }}
