name: Helm

on:
  push:
    branches:
    - 'main'

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup go
      uses: actions/setup-go@v3
      with:
        go-version: '1.19'

    - name: Go cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
          ~/.magefile
        key: ${{ runner.os }}-golang-${{ hashFiles('**/go.sum') }}

    - name: Install mage
      run: go install github.com/magefile/mage@latest

    - name: Compile mage
      run: mage -compile ~/go/bin/mage

    - name: Mage cache
      uses: actions/cache@v3
      with:
        path: ~/go/bin/mage
        key: ${{ runner.os }}-mage-${{ hashFiles('magefile.go') }}

  lint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Mage cache
      uses: actions/cache@v3
      with:
        path: ~/go/bin/mage
        key: ${{ runner.os }}-mage-${{ hashFiles('magefile.go') }}

    - run: ~/go/bin/mage lint

  Update-registry:
    runs-on: ubuntu-latest
    needs: lint
    environment: main
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Mage cache
      uses: actions/cache@v3
      with:
        path: ~/go/bin/mage
        key: ${{ runner.os }}-mage-${{ hashFiles('magefile.go') }}

    - name: Build Helm packages
      run: ~/go/bin/mage build

    - name: Push Helm packages to registry
      run: ~/go/bin/mage push
      env:
        USERNAME: ${{ secrets.USERNAME }}
        TOKEN: ${{ secrets.TOKEN }}
