name: Build

on:
  push:
    branches:
    - 'main'

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: '1.19'

    - uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
          ~/.magefile
        key: ${{ runner.os }}-golang-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-golang-

    - run: go install github.com/magefile/mage@latest
    - run: mage -compile ~/go/bin/mage

    - uses: actions/cache@v3
      with:
        path: ~/go/bin/mage
        key: ${{ runner.os }}-mage-${{ hashFiles('magefile.go') }}
        restore-keys: |
          ${{ runner.os }}-mage-

  lint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
    - uses: actions/checkout@v3

    - uses: actions/cache@v3
      with:
        path: ~/go/bin/mage
        key: ${{ runner.os }}-mage-${{ hashFiles('magefile.go') }}
        restore-keys: |
          ${{ runner.os }}-mage-

    - run: ~/go/bin/mage lint

  package:
    runs-on: ubuntu-latest
    needs: setup
    steps:
    - uses: actions/checkout@v3
    - uses: actions/checkout@v3
      with:
        ref: registry
        path: charts

    - uses: actions/cache@v3
      with:
        path: ~/go/bin/mage
        key: ${{ runner.os }}-mage-${{ hashFiles('magefile.go') }}
        restore-keys: |
          ${{ runner.os }}-mage-

    - run: ~/go/bin/mage package
    - run: ~/go/bin/mage index
    - run: ~/go/bin/mage -v push
