name: Feature

on:
  push:
    branches:
      - feature/*

jobs:
  Lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - User
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Helm lint ${{ matrix.package }}
        uses: lab42/Helm@21.6.2
        with:
          helm: lint ${{ matrix.package }}
