replicaCount: 1

image:
  repository: ghcr.io/lab42/gateway
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v0.0.1-debug"

imagePullSecrets:
- name: "ghcr-image-pull-secret"
nameOverride: ""
fullnameOverride: "gateway"

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations:
  linkerd.io/inject: enabled

podSecurityContext:
  fsGroup: 2000

securityContext: {}
capabilities:
  drop:
  - ALL
readOnlyRootFilesystem: true
runAsNonRoot: true
runAsUser: 1000

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: ""
  annotations:
    kubernetes.io/ingress.class: nginx
  # kubernetes.io/tls-acme: "true"
  hosts:
  - host: gql.k3s.home
    paths:
    - path: /
      pathType: Prefix
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
limits:
  cpu: 100m
  memory: 128Mi
requests:
  cpu: 100m
  memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
